# Generated by Django 5.0.6 on 2024-06-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='text',
            new_name='Texto',
        ),
    ]
