# Generated by Django 5.0.6 on 2024-06-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_rename_text_user_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
